# Generated by Django 5.2.17 on 2026-09-28 22:21

from django.db import migrations, models

INSTAGRAM = "https://www.instagram.com/vaylidenl/"


def zet_instagram(apps, schema_editor):
    # Het Instagram-account van Vaylide (zonder volgparameters). Alleen invullen als het veld nog leeg is.
    SiteConfig = apps.get_model("core", "SiteConfig")
    SiteConfig.objects.filter(instagram_url="").update(instagram_url=INSTAGRAM)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='instagram_url',
            field=models.URLField(blank=True, default=INSTAGRAM, help_text='Volledige link, bijv. https://www.instagram.com/vaylide/. Leeg = geen icoon in de voettekst.', verbose_name='Instagram-pagina'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='Volledige link, bijv. https://www.tiktok.com/@vaylide. Leeg = geen icoon in de voettekst.', verbose_name='TikTok-pagina'),
        ),
        migrations.RunPython(zet_instagram, migrations.RunPython.noop),
    ]
