# Generated by Django 5.2.17 on 2026-09-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundemail',
            name='attach_terms_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
