# Generated by Django 5.2.17 on 2026-09-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name='nieuwsbrief'),
        ),
        migrations.AddField(
            model_name='user',
            name='newsletter_consent',
            field=models.CharField(blank=True, max_length=300, verbose_name='tekst bij de toestemming'),
        ),
        migrations.AddField(
            model_name='user',
            name='newsletter_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='nieuwsbrief sinds'),
        ),
    ]
