# Generated by Django 5.2.17 on 2026-09-29 07:52

import django.db.models.deletion
import gezichten.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitations', '0004_alter_mediaasset_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('consent_text', models.TextField(blank=True)),
                ('photo_bride', models.FileField(blank=True, max_length=255, upload_to=gezichten.models.private_path)),
                ('photo_groom', models.FileField(blank=True, max_length=255, upload_to=gezichten.models.private_path)),
                ('status', models.CharField(choices=[('nieuw', 'Nog geen voorbeeld'), ('bezig', 'Voorbeeld wordt gemaakt'), ('klaar', 'Voorbeeld klaar om te bekijken'), ('goedgekeurd', 'Goedgekeurd'), ('mislukt', 'Mislukt')], default='nieuw', max_length=12)),
                ('attempts_used', models.PositiveSmallIntegerField(default=0)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('extra_attempts', models.PositiveSmallIntegerField(default=0, help_text='Extra pogingen, alleen door het beheer toe te kennen.')),
                ('result', models.FileField(blank=True, max_length=255, upload_to=gezichten.models.private_path)),
                ('result_attempt', models.PositiveSmallIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='invitations.mediaasset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_request', to='invitations.invitation')),
            ],
            options={
                'verbose_name': 'eigen gezichten',
                'verbose_name_plural': 'eigen gezichten',
            },
        ),
    ]
