# Generated by Django 5.2.17 on 2026-09-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gezichten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facerequest',
            name='hair_man',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='facerequest',
            name='hair_woman',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
