"""Beschrijving van de 30 Atelier-ontwerpen: 5 per gelegenheid, elk met drie kleurvarianten.

Gebruikt door tools/atelier/ontwerpen.py. Kleuren worden bij het schrijven op contrast gecontroleerd.
"""

DESIGNS = [
    # ---------------------------------------------------------------- Bruiloft
    {
        "slug": "eucalyptus", "name": "Eucalyptus", "sort_order": 110,
        "tagline": "Botanisch en licht, met eucalyptustakjes",
        "description": "Een vouwkaart met eucalyptustakjes. Na een tik vouwt de kaart open. Sierlijke namen, een foto in boogvorm en rustige lijnen.",
        "style_notes": "Salie, zacht papier, sierlijke letters",
        "occasions": ["bruiloft", "verloving", "jubileum"],
        "atelier": {"opening": "vouwkaart", "hero": "klassiek", "sections": "lijnen", "heading": "ornament", "names": "script", "date": "blok", "photo": "boog", "texture": "papier", "ornament": "eucalyptus"},
        "effects": {"sfeer": "bladeren", "knal": "bladeren", "viering": "bladeren", "namen": "schrijf", "onthul": "zacht", "extra": ["kenburns", "kantel"]},
        "fonts": {"display": "cormorant", "body": "cormorant", "script": "greatvibes", "ui": "jost"},
        "preload": ["script", "display"],
        "tokens": {"--a-names-font": "var(--a-script)", "--a-radius": "4px", "--inv-font-size": "1.12rem"},
        "css": ".a-names { color: var(--a-text); }\n.a-lead { font-style: italic; }",
        "palettes": [
            {"key": "salie", "name": "Salie", "colors": {"bg": "#F4F3EC", "surface": "#FDFCF8", "ink": "#2C3328", "muted": "#5A6254", "accent": "#56684B", "accent_ink": "#FFFFFF", "line": "#D5D9CC", "c2": "#C9D3C0", "c3": "#E6D8C3", "cover_bg": "#E6EADF", "cover_ink": "#2C3328"}},
            {"key": "olijf", "name": "Olijf", "colors": {"bg": "#F3F1E7", "surface": "#FDFCF7", "ink": "#2F2E22", "muted": "#5E5C4C", "accent": "#646032", "accent_ink": "#FFFFFF", "line": "#DAD6C4", "c2": "#D9D6B8", "c3": "#EAD9C6", "cover_bg": "#E7E4D5", "cover_ink": "#2F2E22"}},
            {"key": "dauw", "name": "Dauw", "colors": {"bg": "#EEF2EF", "surface": "#FBFCFB", "ink": "#22302C", "muted": "#52605B", "accent": "#3F6259", "accent_ink": "#FFFFFF", "line": "#CFDAD5", "c2": "#C4D6CF", "c3": "#E5DCD0", "cover_bg": "#DFE8E3", "cover_ink": "#22302C"}},
        ],
    },
    {
        "slug": "gatsby", "name": "Gatsby", "sort_order": 120,
        "tagline": "Art deco in zwart en goud",
        "description": "Een gouden gordijn schuift open. Daarachter een kader met art-decolijnen, strakke hoofdletters en de datum in cijfers.",
        "style_notes": "Zwart en goud, art deco, strakke hoofdletters",
        "occasions": ["bruiloft", "jubileum", "zakelijk"],
        "atelier": {"opening": "gordijn", "hero": "kader", "sections": "midden", "heading": "kapitaal", "names": "kapitaal", "date": "cijfers", "photo": "recht", "texture": "geen", "ornament": "deco"},
        "effects": {"sfeer": "goudstof", "knal": "vonken", "viering": "vonken", "namen": "folie", "onthul": "zoom", "extra": ["stralen", "kantel"]},
        "fonts": {"display": "marcellus", "body": "josefin", "ui": "josefin"},
        "preload": ["display", "body"],
        "tokens": {"--a-radius": "0px", "--a-names-spacing": ".14em"},
        "css": ".a-kicker { letter-spacing: .38em; }\n.a-frame { background: var(--a-surface); }\n.a-sec__body { font-weight: 300; }\n.a-h2 { letter-spacing: .32em; }",
        "palettes": [
            {"key": "zwart-goud", "name": "Zwart & goud", "colors": {"bg": "#121212", "surface": "#1A1A1A", "ink": "#F3EBDD", "muted": "#CBBFAB", "accent": "#D4B36A", "accent_ink": "#121212", "line": "#3A342A", "c2": "#7D6A43", "c3": "#2A2620", "cover_bg": "#0B0B0B", "cover_ink": "#F3EBDD", "curtain": "#2E2618", "scheme": "dark"}},
            {"key": "nachtblauw", "name": "Nachtblauw & goud", "colors": {"bg": "#0F1626", "surface": "#161F33", "ink": "#F1EADB", "muted": "#C6BEAD", "accent": "#D8BC7C", "accent_ink": "#0F1626", "line": "#2E3850", "c2": "#806C45", "c3": "#1E2840", "cover_bg": "#0A1020", "cover_ink": "#F1EADB", "curtain": "#1C2946", "scheme": "dark"}},
            {"key": "ivoor", "name": "Ivoor & goud", "colors": {"bg": "#FAF6EC", "surface": "#FFFDF7", "ink": "#1D1B16", "muted": "#5B5446", "accent": "#7E5F27", "accent_ink": "#FFFFFF", "line": "#E4D9C2", "c2": "#E6D3A8", "c3": "#F1EAD9", "cover_bg": "#1D1B16", "cover_ink": "#F6EEDC", "cover_btn": "#D4B36A", "cover_btn_ink": "#1D1B16", "curtain": "#8C6A2F"}},
        ],
    },
]

DESIGNS += [
    {
        "slug": "rozentuin", "name": "Rozentuin", "sort_order": 130,
        "tagline": "Romantisch, met rozen en sierlijk schrift",
        "description": "Een envelop met zegel opent zich en de kaart schuift naar buiten. Bloemen, een ronde foto en elke sectie op een eigen kaartje.",
        "style_notes": "Zacht roze, bloemen, sierlijk handschrift",
        "occasions": ["bruiloft", "verloving", "babyshower"],
        "atelier": {"opening": "envelop", "hero": "klassiek", "sections": "kaarten", "heading": "script", "names": "script", "date": "lijn", "photo": "cirkel", "texture": "geen", "ornament": "bloemen"},
        "effects": {"sfeer": "blaadjes", "knal": "blaadjes", "viering": "harten", "namen": "schrijf", "onthul": "omhoog", "extra": ["kenburns", "kantel", "tik"]},
        "fonts": {"display": "ebgaramond", "body": "ebgaramond", "script": "parisienne", "ui": "figtree"},
        "preload": ["script", "display"],
        "tokens": {"--a-names-font": "var(--a-script)", "--a-radius": "14px", "--inv-font-size": "1.1rem"},
        "css": ".a-names { color: var(--a-text); }\n.a-sec-kaarten .a-sec { box-shadow: none; border: 1px solid var(--a-line); }\n.a-date--lijn { font-style: italic; }",
        "palettes": [
            {"key": "blush", "name": "Blush", "colors": {"bg": "#FBF3F1", "surface": "#FFFFFF", "ink": "#3A2A2E", "muted": "#6A565B", "accent": "#9E4A63", "accent_ink": "#FFFFFF", "line": "#EFDCDD", "c2": "#F2C9CF", "c3": "#CFDCC6", "cover_bg": "#F5E4E3", "cover_ink": "#3A2A2E", "env": "#F0D6D6"}},
            {"key": "perzik", "name": "Perzik", "colors": {"bg": "#FCF4EC", "surface": "#FFFFFF", "ink": "#3B2A22", "muted": "#6B584C", "accent": "#9C5132", "accent_ink": "#FFFFFF", "line": "#F0DECF", "c2": "#F5CDB4", "c3": "#D6DDC4", "cover_bg": "#F6E6D8", "cover_ink": "#3B2A22", "env": "#F2DCC8"}},
            {"key": "lila", "name": "Lila", "colors": {"bg": "#F7F3F9", "surface": "#FFFFFF", "ink": "#2F2836", "muted": "#625A6B", "accent": "#72528A", "accent_ink": "#FFFFFF", "line": "#E6DDEC", "c2": "#DCC9E8", "c3": "#D3E0CE", "cover_bg": "#ECE3F1", "cover_ink": "#2F2836", "env": "#E4D6EC"}},
        ],
    },
    {
        "slug": "lijnenspel", "name": "Lijnenspel", "sort_order": 140,
        "tagline": "Minimalistisch en redactioneel",
        "description": "Een zachte sluier trekt op. Grote, strakke letters links uitgelijnd, de feiten in kolommen en veel witruimte.",
        "style_notes": "Zwart-wit, grote letters, veel witruimte",
        "occasions": ["bruiloft", "verloving", "zakelijk"],
        "atelier": {"opening": "sluier", "hero": "redactioneel", "sections": "tweekolom", "heading": "groot", "names": "display", "date": "cijfers", "photo": "recht", "texture": "geen", "ornament": "lijnen"},
        "effects": {"sfeer": "stofjes", "knal": "lijnen", "viering": "lijnen", "namen": "zacht", "onthul": "wissel", "extra": ["kenburns"]},
        "fonts": {"display": "bodoni", "body": "manrope", "ui": "manrope"},
        "preload": ["display", "body"],
        "tokens": {"--a-radius": "0px", "--a-names-weight": "500", "--a-names-spacing": "-.035em"},
        "css": ".a-tagline { font-style: normal; font-family: var(--a-ui); }\n.a-lead { font-family: var(--a-display); font-style: italic; }\n.a-h2 { font-weight: 500; }",
        "palettes": [
            {"key": "wit", "name": "Wit", "colors": {"bg": "#FFFFFF", "surface": "#F6F6F4", "ink": "#111111", "muted": "#595959", "accent": "#111111", "accent_ink": "#FFFFFF", "line": "#DDDDDD", "c2": "#E9E9E6", "c3": "#F2EEE8", "cover_bg": "#FFFFFF", "cover_ink": "#111111"}},
            {"key": "zand", "name": "Zand", "colors": {"bg": "#F1ECE4", "surface": "#FAF7F2", "ink": "#1E1B17", "muted": "#5C554C", "accent": "#5E4529", "accent_ink": "#FFFFFF", "line": "#D9D0C3", "c2": "#E3D6C4", "c3": "#EDE5D8", "cover_bg": "#F1ECE4", "cover_ink": "#1E1B17"}},
            {"key": "grafiet", "name": "Grafiet", "colors": {"bg": "#1C1C1C", "surface": "#262626", "ink": "#F2F0EC", "muted": "#BDB8B0", "accent": "#F2F0EC", "accent_ink": "#1C1C1C", "line": "#3A3A3A", "c2": "#4A4A4A", "c3": "#333333", "cover_bg": "#1C1C1C", "cover_ink": "#F2F0EC", "scheme": "dark"}},
        ],
    },
    {
        "slug": "zuiden", "name": "Zuiden", "sort_order": 150,
        "tagline": "Warm en zonnig, met aardetinten",
        "description": "Een cadeaulint wordt losgetrokken. Terracotta, een zon, een foto in boogvorm naast de tekst en een kalenderblaadje voor de datum.",
        "style_notes": "Terracotta en oker, zon, linnen",
        "occasions": ["bruiloft", "verjaardag", "jubileum"],
        "atelier": {"opening": "lint", "hero": "gesplitst", "sections": "kaarten", "heading": "lijn", "names": "cursief", "date": "kalender", "photo": "boog", "texture": "linnen", "ornament": "zon"},
        "effects": {"sfeer": "zonlicht", "knal": "blaadjes", "viering": "blaadjes", "namen": "zacht", "onthul": "zacht", "extra": ["stralen", "kenburns", "kantel"]},
        "fonts": {"display": "fraunces", "body": "jost", "ui": "jost"},
        "preload": ["display", "body"],
        "tokens": {"--a-radius": "10px", "--a-names-weight": "400"},
        "css": ".a-names { color: var(--a-text); }\n.a-photo--boog .a-photo__img { box-shadow: 0 0 0 8px var(--a-surface), 0 24px 40px -26px rgba(0, 0, 0, .5); }",
        "palettes": [
            {"key": "terracotta", "name": "Terracotta", "colors": {"bg": "#F6EEE6", "surface": "#FFFBF7", "ink": "#33241C", "muted": "#67554A", "accent": "#A0472A", "accent_ink": "#FFFFFF", "line": "#E4D3C3", "c2": "#E7B79B", "c3": "#C9C39B", "cover_bg": "#EADBCB", "cover_ink": "#33241C"}},
            {"key": "oker", "name": "Oker", "colors": {"bg": "#F7F0E1", "surface": "#FFFBF2", "ink": "#33271A", "muted": "#66584A", "accent": "#865515", "accent_ink": "#FFFFFF", "line": "#E6D8BD", "c2": "#EBCB8B", "c3": "#C9B99A", "cover_bg": "#EDE0C5", "cover_ink": "#33271A"}},
            {"key": "olijf", "name": "Olijf", "colors": {"bg": "#F2F0E4", "surface": "#FCFBF5", "ink": "#2B2B1F", "muted": "#5D5C4B", "accent": "#5A5F2F", "accent_ink": "#FFFFFF", "line": "#DEDBC6", "c2": "#D6D3A8", "c3": "#E3C3A5", "cover_bg": "#E6E3D1", "cover_ink": "#2B2B1F"}},
        ],
    },
    # ---------------------------------------------------------------- Verloving
    {
        "slug": "ja-woord", "name": "Ja-woord", "sort_order": 160,
        "tagline": "Elegant, met jullie initialen groot in beeld",
        "description": "Een cadeaulint wordt losgetrokken. Jullie initialen staan groot op de achtergrond, met twee ringen en een sierlijke kop.",
        "style_notes": "Champagne, monogram, ringen",
        "occasions": ["verloving", "bruiloft"],
        "atelier": {"opening": "lint", "hero": "monogram", "sections": "midden", "heading": "script", "names": "kapitaal", "date": "lijn", "photo": "cirkel", "texture": "geen", "ornament": "ringen"},
        "effects": {"sfeer": "champagne", "knal": "champagne", "viering": "harten", "namen": "folie", "onthul": "zoom", "extra": ["kantel", "tik"]},
        "fonts": {"display": "italiana", "body": "tenor", "script": "greatvibes", "ui": "tenor", "text": "instrument", "number": "instrument"},
        "preload": ["display", "script"],
        "tokens": {"--a-names-spacing": ".18em"},
        "css": ".a-kicker { font-family: var(--a-script); font-size: clamp(2rem, 8vw, 2.6rem); font-weight: 400; letter-spacing: 0; text-transform: none; }\n.a-monogram { font-size: clamp(8rem, 40vw, 16rem); letter-spacing: .02em; }",
        "palettes": [
            {"key": "champagne", "name": "Champagne", "colors": {"bg": "#F8F3EA", "surface": "#FFFDF8", "ink": "#2E271F", "muted": "#645849", "accent": "#826339", "accent_ink": "#FFFFFF", "line": "#E6DCCB", "c2": "#EAD7BA", "c3": "#F1E3E0", "cover_bg": "#EFE5D6", "cover_ink": "#2E271F", "ribbon": "#C9A76A"}},
            {"key": "blush", "name": "Blush", "colors": {"bg": "#FAF0EE", "surface": "#FFFFFF", "ink": "#35262A", "muted": "#68565A", "accent": "#94455B", "accent_ink": "#FFFFFF", "line": "#EFDADA", "c2": "#F1CDD2", "c3": "#EADCC9", "cover_bg": "#F3E1DF", "cover_ink": "#35262A", "ribbon": "#D9A2AE"}},
            {"key": "nacht", "name": "Nacht", "colors": {"bg": "#1E1B22", "surface": "#28242D", "ink": "#F4EDE6", "muted": "#C9BDB5", "accent": "#D9B99B", "accent_ink": "#1E1B22", "line": "#3B3542", "c2": "#8E7866", "c3": "#4A4152", "cover_bg": "#17151A", "cover_ink": "#F4EDE6", "ribbon": "#D9B99B", "scheme": "dark"}},
        ],
    },
    {
        "slug": "polaroid", "name": "Polaroid", "sort_order": 170,
        "tagline": "Speels, met handgeschreven letters en foto's",
        "description": "Een polaroid ontwikkelt zich na een tik. Handgeschreven koppen, schuin geplakte kaartjes en kleine hartjes.",
        "style_notes": "Kraftpapier, polaroids, handschrift",
        "occasions": ["verloving", "verjaardag", "jubileum"],
        "atelier": {"opening": "polaroid", "hero": "polaroid", "sections": "kaarten", "heading": "script", "names": "script", "date": "lijn", "photo": "polaroid", "texture": "papier", "ornament": "harten"},
        "effects": {"sfeer": "harten", "knal": "flits", "viering": "harten", "namen": "schrijf", "onthul": "kanteling", "extra": ["tik"]},
        "fonts": {"display": "nunito", "body": "nunito", "script": "caveat", "ui": "nunito"},
        "preload": ["script", "body"],
        "tokens": {"--a-names-font": "var(--a-script)", "--a-radius": "4px", "--a-names-scale": "1.08"},
        "css": ".a-sec-kaarten .a-sec { position: relative; box-shadow: 0 10px 24px -18px rgba(0, 0, 0, .5); }\n.a-sec-kaarten .a-sec:nth-child(odd) { rotate: -.7deg; }\n.a-sec-kaarten .a-sec:nth-child(even) { rotate: .6deg; }\n.a-sec-kaarten .a-sec:not(.a-welcome)::before { content: \"\"; position: absolute; top: -11px; left: 50%; width: 96px; height: 22px; margin-left: -48px; background: color-mix(in srgb, var(--a-c2) 75%, transparent); rotate: -3deg; }\n.a-tagline { font-family: var(--a-script); font-style: normal; font-size: 1.6rem; }\n.a-date--lijn { font-family: var(--a-script); font-size: 1.8rem; }",
        "palettes": [
            {"key": "kraft", "name": "Kraft", "colors": {"bg": "#EFE4D2", "surface": "#FBF7F0", "ink": "#2E2620", "muted": "#5E5247", "accent": "#9C3632", "accent_ink": "#FFFFFF", "line": "#D9C8AF", "c2": "#E7B8A5", "c3": "#B7C7B0", "cover_bg": "#E4D6BF", "cover_ink": "#2E2620"}},
            {"key": "wit", "name": "Wit", "colors": {"bg": "#F7F6F2", "surface": "#FFFFFF", "ink": "#24272B", "muted": "#595E63", "accent": "#2D5A87", "accent_ink": "#FFFFFF", "line": "#E2E0DA", "c2": "#F6D98B", "c3": "#BFD5E6", "cover_bg": "#ECEAE4", "cover_ink": "#24272B"}},
            {"key": "zwart", "name": "Zwart", "colors": {"bg": "#232323", "surface": "#2E2E2E", "ink": "#F3EFE7", "muted": "#C4BCB0", "accent": "#F2C14E", "accent_ink": "#232323", "line": "#403F3C", "c2": "#E07A5F", "c3": "#81B29A", "cover_bg": "#1B1B1B", "cover_ink": "#F3EFE7", "scheme": "dark"}},
        ],
    },
    {
        "slug": "sterrennacht", "name": "Onder de sterren", "sort_order": 180,
        "tagline": "Sfeervol, met een sterrenhemel en de maan",
        "description": "Een sterrenhemel schuift omhoog. Daaronder een grote foto met jullie namen erop, sterren en een maansikkel.",
        "style_notes": "Middernachtblauw, sterren, maan",
        "occasions": ["verloving", "bruiloft", "jubileum"],
        "atelier": {"opening": "sterren", "hero": "volbeeld", "sections": "midden", "heading": "kapitaal", "names": "cursief", "date": "blok", "photo": "rond", "texture": "sterren", "ornament": "sterren"},
        "effects": {"sfeer": "sterren", "knal": "sterren", "viering": "sterren", "namen": "zacht", "onthul": "zacht", "extra": ["kenburns"]},
        "fonts": {"display": "cormorant", "body": "josefin", "ui": "josefin"},
        "preload": ["display", "body"],
        "tokens": {"--a-names-weight": "500"},
        "css": ".a-sec__body { font-weight: 300; }\n.a-hero__bg::after { background: linear-gradient(180deg, color-mix(in srgb, var(--a-cover-bg) 72%, transparent), color-mix(in srgb, var(--a-cover-bg) 88%, transparent)); }",
        "palettes": [
            {"key": "middernacht", "name": "Middernacht", "colors": {"bg": "#0E1630", "surface": "#16203F", "ink": "#F1ECE2", "muted": "#C3C2CC", "accent": "#E8C987", "accent_ink": "#0E1630", "line": "#2C3760", "c2": "#E8C987", "c3": "#9FB3D9", "cover_bg": "#0B1128", "cover_ink": "#F6F1E7", "scheme": "dark"}},
            {"key": "aubergine", "name": "Aubergine", "colors": {"bg": "#1E1427", "surface": "#291C35", "ink": "#F4ECE8", "muted": "#CDBFC8", "accent": "#E6B8A2", "accent_ink": "#1E1427", "line": "#3D2D4C", "c2": "#E6B8A2", "c3": "#B39CD0", "cover_bg": "#170F1F", "cover_ink": "#F4ECE8", "scheme": "dark"}},
            {"key": "inkt", "name": "Inkt", "colors": {"bg": "#10151B", "surface": "#18202A", "ink": "#EEF1F4", "muted": "#B9C1CA", "accent": "#C8D3DE", "accent_ink": "#10151B", "line": "#2A3340", "c2": "#C8D3DE", "c3": "#8FA3B8", "cover_bg": "#0B0F14", "cover_ink": "#EEF1F4", "scheme": "dark"}},
        ],
    },
    {
        "slug": "pampas", "name": "Pampas", "sort_order": 190,
        "tagline": "Boho en naturel, met pampasgras",
        "description": "Een zachte sluier trekt op. Pampasgras, een hoge foto in boogvorm, hoofdletters met veel ruimte en linnen tinten.",
        "style_notes": "Zand, pampasgras, linnen",
        "occasions": ["verloving", "bruiloft", "babyshower"],
        "atelier": {"opening": "sluier", "hero": "klassiek", "sections": "lijnen", "heading": "ornament", "names": "kapitaal", "date": "lijn", "photo": "boog", "texture": "linnen", "ornament": "pampas"},
        "effects": {"sfeer": "pluisjes", "knal": "pluisjes", "viering": "pluisjes", "namen": "zacht", "onthul": "zacht", "extra": ["kenburns", "aura"]},
        "fonts": {"display": "gilda", "body": "jost", "ui": "jost"},
        "preload": ["display", "body"],
        "tokens": {"--a-names-spacing": ".2em", "--a-radius": "6px"},
        "css": ".a-photo--boog { width: min(100%, 22rem); }\n.a-photo--boog .a-photo__img { aspect-ratio: 3 / 5; }\n.a-sec__body { font-weight: 300; }",
        "palettes": [
            {"key": "zand", "name": "Zand", "colors": {"bg": "#F4EDE3", "surface": "#FBF7F1", "ink": "#3B3027", "muted": "#685B4E", "accent": "#7F5C3E", "accent_ink": "#FFFFFF", "line": "#E2D5C4", "c2": "#E5D2B8", "c3": "#D9C7B0", "cover_bg": "#EDE2D3", "cover_ink": "#3B3027"}},
            {"key": "roest", "name": "Roest", "colors": {"bg": "#F3E9E1", "surface": "#FBF6F2", "ink": "#3A2A22", "muted": "#67544A", "accent": "#944725", "accent_ink": "#FFFFFF", "line": "#E4D2C5", "c2": "#E9C1A6", "c3": "#D8C9B4", "cover_bg": "#EBDDD1", "cover_ink": "#3A2A22"}},
            {"key": "taupe", "name": "Taupe", "colors": {"bg": "#EFEBE6", "surface": "#F9F7F4", "ink": "#2F2A26", "muted": "#5F5852", "accent": "#5E544D", "accent_ink": "#FFFFFF", "line": "#DCD5CD", "c2": "#D8CFC4", "c3": "#E4DCD0", "cover_bg": "#E6E0D9", "cover_ink": "#2F2A26"}},
        ],
    },
    {
        "slug": "monogram", "name": "Monogram", "sort_order": 200,
        "tagline": "Klassiek en strak, met een gekleurde band",
        "description": "Een paneel schuift opzij. Bovenaan een gekleurde band met jullie namen onder elkaar, genummerde onderdelen en de datum in een cirkel.",
        "style_notes": "Marine, strak, genummerd",
        "occasions": ["verloving", "bruiloft", "zakelijk"],
        "atelier": {"opening": "schuif", "hero": "band", "sections": "genummerd", "heading": "kapitaal", "names": "stapel", "date": "cirkel", "photo": "cirkel", "texture": "geen", "ornament": "geometrisch"},
        "effects": {"sfeer": "geometrie", "knal": "lijnen", "viering": "vonken", "namen": "zacht", "onthul": "wissel", "extra": []},
        "fonts": {"display": "bodoni", "body": "montserrat", "ui": "montserrat"},
        "preload": ["display", "body"],
        "tokens": {"--a-radius": "2px"},
        "css": ".a-sec__body { font-size: 1rem; }\n.a-band .a-names { font-style: italic; }",
        "palettes": [
            {"key": "marine", "name": "Marine", "colors": {"bg": "#F5F4F0", "surface": "#FFFFFF", "ink": "#1B2233", "muted": "#555C6B", "accent": "#1F2A44", "accent_ink": "#FFFFFF", "line": "#DCDDE2", "c2": "#C9CFDC", "c3": "#E7E2D6", "cover_bg": "#1F2A44", "cover_ink": "#F5F4F0"}},
            {"key": "bordeaux", "name": "Bordeaux", "colors": {"bg": "#F7F2F0", "surface": "#FFFFFF", "ink": "#2C1B1F", "muted": "#634F54", "accent": "#5C1F2B", "accent_ink": "#FFFFFF", "line": "#E6DADA", "c2": "#E2C3C8", "c3": "#EDE3D6", "cover_bg": "#5C1F2B", "cover_ink": "#F7F2F0"}},
            {"key": "smaragd", "name": "Smaragd", "colors": {"bg": "#F1F4F1", "surface": "#FFFFFF", "ink": "#16271F", "muted": "#4F5E56", "accent": "#1E4A3B", "accent_ink": "#FFFFFF", "line": "#D6DED8", "c2": "#C3D6CC", "c3": "#E6E4D8", "cover_bg": "#1E4A3B", "cover_ink": "#F1F4F1"}},
        ],
    },
    # ---------------------------------------------------------------- Verjaardag
    {
        "slug": "confetti", "name": "Confetti", "sort_order": 210,
        "tagline": "Vrolijk en kleurrijk, met een groot getal",
        "description": "Een tik en de confetti vliegt in het rond. De leeftijd staat groot in beeld, met vrolijke kaartjes en een kalenderblaadje.",
        "style_notes": "Kleurrijk, confetti, groot getal",
        "occasions": ["verjaardag", "babyshower", "zakelijk"],
        "atelier": {"opening": "confetti", "hero": "getal", "sections": "kaarten", "heading": "groot", "names": "display", "date": "kalender", "photo": "cirkel", "texture": "confetti", "ornament": "confetti"},
        "effects": {"sfeer": "confetti", "knal": "kanon", "viering": "kanon", "namen": "pop", "onthul": "zoom", "extra": ["tik"]},
        "fonts": {"display": "fredoka", "body": "nunito", "ui": "nunito"},
        "preload": ["display", "body"],
        "tokens": {"--a-radius": "18px", "--a-names-weight": "600", "--a-h2-weight": "600"},
        "css": ".a-number { font-weight: 700; text-shadow: .045em .045em 0 var(--a-c2), .09em .09em 0 var(--a-c3); }\n.a-tagline { font-family: var(--a-body); font-style: normal; }\n.a-lead { font-family: var(--a-body); }",
        "palettes": [
            {"key": "vrolijk", "name": "Vrolijk", "colors": {"bg": "#FFF8F0", "surface": "#FFFFFF", "ink": "#2B2320", "muted": "#645750", "accent": "#B83C0B", "accent_ink": "#FFFFFF", "line": "#F2E3D3", "c2": "#FFC857", "c3": "#5FC8D8", "cover_bg": "#FFF1E3", "cover_ink": "#2B2320"}},
            {"key": "pastel", "name": "Pastel", "colors": {"bg": "#F7F4FF", "surface": "#FFFFFF", "ink": "#29243A", "muted": "#5E586F", "accent": "#5B3FCB", "accent_ink": "#FFFFFF", "line": "#E4DEF5", "c2": "#FFB5C2", "c3": "#9ED9CC", "cover_bg": "#EFEAFF", "cover_ink": "#29243A"}},
            {"key": "nacht", "name": "Nacht", "colors": {"bg": "#161616", "surface": "#222222", "ink": "#F7F3EC", "muted": "#C8C0B4", "accent": "#FFD23F", "accent_ink": "#161616", "line": "#363636", "c2": "#FF6B9A", "c3": "#3EC1D3", "cover_bg": "#101010", "cover_ink": "#F7F3EC", "scheme": "dark"}},
        ],
    },
    {
        "slug": "neon", "name": "Neonnacht", "sort_order": 220,
        "tagline": "Feestelijk en donker, met gloeiende letters",
        "description": "Een sluier trekt op en de letters gaan gloeien als neon. Een groot getal, strakke lijnen en een donkere achtergrond.",
        "style_notes": "Donker, neonlicht, gloeiende letters",
        "occasions": ["verjaardag", "zakelijk"],
        "atelier": {"opening": "sluier", "hero": "getal", "sections": "lijnen", "heading": "groot", "names": "display", "date": "cijfers", "photo": "rond", "texture": "geen", "ornament": "lijnen"},
        "effects": {"sfeer": "neon", "knal": "neon", "viering": "neon", "namen": "gloed", "onthul": "zacht", "extra": ["tik"]},
        "fonts": {"display": "tiltneon", "body": "manrope", "ui": "manrope"},
        "preload": ["display", "body"],
        "tokens": {"--a-radius": "14px"},
        "css": ".a-names, .a-number, .a-h2, .a-cover__title, .a-cover__big { text-shadow: 0 0 4px color-mix(in srgb, var(--a-accent) 80%, transparent), 0 0 18px color-mix(in srgb, var(--a-accent) 55%, transparent), 0 0 40px color-mix(in srgb, var(--a-accent) 35%, transparent); }\n.a-number { color: var(--a-ink); }\n.a-sec-lijnen .a-sec + .a-sec { border-top-color: color-mix(in srgb, var(--a-accent) 60%, transparent); }\n.a-photo--rond .a-photo__img { box-shadow: 0 0 0 2px var(--a-accent), 0 0 28px color-mix(in srgb, var(--a-accent) 45%, transparent); }\n.a-tagline { font-family: var(--a-body); font-style: normal; }",
        "palettes": [
            {"key": "roze", "name": "Roze neon", "colors": {"bg": "#120B1E", "surface": "#1C1330", "ink": "#FBF3FF", "muted": "#CDBFDD", "accent": "#FF4FD8", "accent_ink": "#120B1E", "accent_text": "#FF8AE5", "line": "#3A2656", "c2": "#7A2FF7", "c3": "#2DE2E6", "cover_bg": "#0D0716", "cover_ink": "#FBF3FF", "scheme": "dark"}},
            {"key": "blauw", "name": "Blauw neon", "colors": {"bg": "#07121F", "surface": "#0E1C2E", "ink": "#EEF8FF", "muted": "#B5C6D6", "accent": "#37E2FF", "accent_ink": "#07121F", "line": "#1D3350", "c2": "#2F6BFF", "c3": "#B06CFF", "cover_bg": "#040C16", "cover_ink": "#EEF8FF", "scheme": "dark"}},
            {"key": "groen", "name": "Groen neon", "colors": {"bg": "#0B1410", "surface": "#122019", "ink": "#F1FFF3", "muted": "#BCD1C2", "accent": "#7CFF6B", "accent_ink": "#0B1410", "line": "#20382C", "c2": "#2EE6A6", "c3": "#E6FF4F", "cover_bg": "#060D09", "cover_ink": "#F1FFF3", "scheme": "dark"}},
        ],
    },
    {
        "slug": "ballonfeest", "name": "Ballonfeest", "sort_order": 230,
        "tagline": "Vrolijk en licht, met ballonnen",
        "description": "Laat de ballonnen los om de uitnodiging te openen. Ronde vormen, ballonnen en de datum in een cirkel.",
        "style_notes": "Pastel, ballonnen, ronde vormen",
        "occasions": ["verjaardag", "babyshower"],
        "atelier": {"opening": "ballonnen", "hero": "klassiek", "sections": "midden", "heading": "groot", "names": "display", "date": "cirkel", "photo": "cirkel", "texture": "geen", "ornament": "ballonnen"},
        "effects": {"sfeer": "ballonnen", "knal": "ballonnen", "viering": "cadeautjes", "namen": "pop", "onthul": "zoom", "extra": ["tik"]},
        "fonts": {"display": "fredoka", "body": "quicksand", "ui": "quicksand"},
        "preload": ["display", "body"],
        "tokens": {"--a-radius": "20px", "--a-names-weight": "600", "--a-h2-weight": "600"},
        "css": ".a-tagline { font-family: var(--a-body); font-style: normal; font-weight: 500; }\n.a-sec__body { font-weight: 500; }\n.a-lead { font-family: var(--a-body); }",
        "palettes": [
            {"key": "pastel", "name": "Pastel", "colors": {"bg": "#FFF7F4", "surface": "#FFFFFF", "ink": "#2F2A33", "muted": "#625A66", "accent": "#B03D62", "accent_ink": "#FFFFFF", "line": "#F3E1DB", "c2": "#F7C8D4", "c3": "#BFE3E0", "cover_bg": "#FFEFEA", "cover_ink": "#2F2A33"}},
            {"key": "fris", "name": "Fris", "colors": {"bg": "#F3FAF7", "surface": "#FFFFFF", "ink": "#1F2D29", "muted": "#51605B", "accent": "#1D7266", "accent_ink": "#FFFFFF", "line": "#D8EAE3", "c2": "#A8E0D1", "c3": "#FFD6A5", "cover_bg": "#E6F4EE", "cover_ink": "#1F2D29"}},
            {"key": "goud", "name": "Goud", "colors": {"bg": "#FBF6EC", "surface": "#FFFFFF", "ink": "#2E2719", "muted": "#615847", "accent": "#7F5D13", "accent_ink": "#FFFFFF", "line": "#EDE1C8", "c2": "#E9CF8F", "c3": "#F3E3C3", "cover_bg": "#F4EAD4", "cover_ink": "#2E2719"}},
        ],
    },
    {
        "slug": "glitter", "name": "Glitter & goud", "sort_order": 240,
        "tagline": "Glamour, met goud en fonkeling",
        "description": "Een zwart cadeau met een gouden strik: plof, en er vliegen cadeautjes en glitter uit. Een groot gouden getal, fonkelende sterretjes, hoofdletters en een donkere achtergrond.",
        "style_notes": "Zwart en goud, fonkeling, glamour",
        "occasions": ["verjaardag", "jubileum", "zakelijk"],
        "atelier": {"opening": "cadeau", "hero": "getal", "sections": "midden", "heading": "kapitaal", "names": "kapitaal", "date": "cijfers", "photo": "rond", "texture": "sterren", "ornament": "fonkel"},
        "effects": {"sfeer": "glitter", "knal": "cadeautjes", "viering": "vonken", "namen": "folie", "onthul": "zoom", "extra": ["disco", "tik"]},
        "fonts": {"display": "abril", "body": "josefin", "ui": "josefin", "text": "instrument"},
        "preload": ["display", "body"],
        "tokens": {"--a-radius": "8px", "--a-names-spacing": ".1em"},
        "css": ".a-number { color: var(--a-text); }\n.a-sec__body { font-weight: 300; }\n.a-names { font-family: var(--a-body); font-weight: 600; }",
        "palettes": [
            {"key": "zwart-goud", "name": "Zwart & goud", "colors": {"bg": "#121212", "surface": "#1C1C1C", "ink": "#F5EFE6", "muted": "#CDC3B5", "accent": "#E1BE6A", "accent_ink": "#121212", "line": "#3A3326", "c2": "#E1BE6A", "c3": "#8C7A52", "cover_bg": "#0A0A0A", "cover_ink": "#F5EFE6", "wrap": "#2A241A", "scheme": "dark"}},
            {"key": "roze-goud", "name": "Roze & goud", "colors": {"bg": "#FFF4F2", "surface": "#FFFFFF", "ink": "#33232A", "muted": "#67545B", "accent": "#94485A", "accent_ink": "#FFFFFF", "line": "#F1DCDB", "c2": "#E7B7A7", "c3": "#D9B26F", "cover_bg": "#33232A", "cover_ink": "#FFF4F2", "cover_btn": "#E7B7A7", "cover_btn_ink": "#33232A", "wrap": "#94485A", "ribbon": "#D9B26F"}},
            {"key": "nacht-zilver", "name": "Nacht & zilver", "colors": {"bg": "#0F1420", "surface": "#171E2D", "ink": "#EEF1F5", "muted": "#BAC2CE", "accent": "#C9D1DC", "accent_ink": "#0F1420", "line": "#2A3346", "c2": "#C9D1DC", "c3": "#6F7C92", "cover_bg": "#0A0E17", "cover_ink": "#EEF1F5", "wrap": "#2A3550", "scheme": "dark"}},
        ],
    },
    {
        "slug": "tropisch", "name": "Tropisch", "sort_order": 250,
        "tagline": "Zomers, met palmbladeren",
        "description": "Een vouwkaart met palmblad opent zich. Een ronde foto naast de tekst, zomerse kleuren en kaartjes voor elk onderdeel.",
        "style_notes": "Jungle, palmbladeren, zomer",
        "occasions": ["verjaardag", "bruiloft", "zakelijk"],
        "atelier": {"opening": "vouwkaart", "hero": "gesplitst", "sections": "kaarten", "heading": "lijn", "names": "cursief", "date": "blok", "photo": "rond", "texture": "geen", "ornament": "palm"},
        "effects": {"sfeer": "blaadjes", "knal": "blaadjes", "viering": "confetti", "namen": "zacht", "onthul": "wissel", "extra": ["kenburns", "kantel"]},
        "fonts": {"display": "fraunces", "body": "quicksand", "ui": "quicksand"},
        "preload": ["display", "body"],
        "tokens": {"--a-radius": "16px", "--a-names-weight": "500"},
        "css": ".a-names { color: var(--a-text); }\n.a-sec__body { font-weight: 500; }\n.a-tagline { font-family: var(--a-body); font-style: normal; font-weight: 500; }",
        "palettes": [
            {"key": "jungle", "name": "Jungle", "colors": {"bg": "#F2F7F1", "surface": "#FFFFFF", "ink": "#1E2B24", "muted": "#4E5D56", "accent": "#1E6A4D", "accent_ink": "#FFFFFF", "line": "#D8E6D9", "c2": "#F4A6A0", "c3": "#F6D28B", "cover_bg": "#E3EFE4", "cover_ink": "#1E2B24"}},
            {"key": "flamingo", "name": "Flamingo", "colors": {"bg": "#FFF3F3", "surface": "#FFFFFF", "ink": "#2E1F23", "muted": "#654F55", "accent": "#A82C51", "accent_ink": "#FFFFFF", "line": "#F5DADC", "c2": "#9FD3B5", "c3": "#F6D28B", "cover_bg": "#FCE4E5", "cover_ink": "#2E1F23"}},
            {"key": "zonsondergang", "name": "Zonsondergang", "colors": {"bg": "#FFF6EC", "surface": "#FFFFFF", "ink": "#2E2116", "muted": "#66564A", "accent": "#A5471A", "accent_ink": "#FFFFFF", "line": "#F3E0CC", "c2": "#F7B267", "c3": "#8FC1B5", "cover_bg": "#FCE8D3", "cover_ink": "#2E2116"}},
        ],
    },
    # ---------------------------------------------------------------- Jubileum
    {
        "slug": "lauwerkrans", "name": "Lauwerkrans", "sort_order": 260,
        "tagline": "Feestelijk en klassiek, met een lauwerkrans",
        "description": "Een envelop met zegel opent zich. Het aantal jaren staat in een lauwerkrans, met klassieke letters en papier.",
        "style_notes": "Goud en ivoor, lauwerkrans, klassiek",
        "occasions": ["jubileum", "bruiloft", "verjaardag"],
        "atelier": {"opening": "envelop", "hero": "getal", "sections": "midden", "heading": "ornament", "names": "display", "date": "blok", "photo": "cirkel", "texture": "papier", "ornament": "lauwerkrans"},
        "effects": {"sfeer": "lauwerblaadjes", "knal": "vonken", "viering": "vonken", "namen": "folie", "onthul": "omhoog", "extra": ["kantel"]},
        "fonts": {"display": "cormorant", "body": "cormorant", "ui": "figtree"},
        "extra_fonts": ["cinzel"],
        "preload": ["display"],
        "tokens": {"--a-names-weight": "500", "--inv-font-size": "1.12rem"},
        "css": ".a-kicker, .a-cover__kicker, .a-env__kicker { font-family: \"Cinzel\", Georgia, serif; letter-spacing: .2em; }\n.a-orn--closing { width: min(8rem, 40vw); }",
        "palettes": [
            {"key": "goud", "name": "Goud", "colors": {"bg": "#FAF6EC", "surface": "#FFFDF8", "ink": "#2A241A", "muted": "#5E5546", "accent": "#7A5B22", "accent_ink": "#FFFFFF", "line": "#E9DFC9", "c2": "#E6D5AE", "c3": "#D7DDC9", "cover_bg": "#EFE6D2", "cover_ink": "#2A241A", "env": "#EBDFC6"}},
            {"key": "zilver", "name": "Zilver", "colors": {"bg": "#F4F5F6", "surface": "#FFFFFF", "ink": "#23272C", "muted": "#575E66", "accent": "#56606C", "accent_ink": "#FFFFFF", "line": "#DEE1E5", "c2": "#D5DAE0", "c3": "#E9E4DC", "cover_bg": "#E6E9EC", "cover_ink": "#23272C", "env": "#DCE0E5"}},
            {"key": "groen", "name": "Groen", "colors": {"bg": "#F2F4EF", "surface": "#FFFFFF", "ink": "#1F2A1D", "muted": "#535D50", "accent": "#3F5A3A", "accent_ink": "#FFFFFF", "line": "#DAE0D5", "c2": "#CED9C5", "c3": "#EAE1C9", "cover_bg": "#E3E9DE", "cover_ink": "#1F2A1D", "env": "#DDE5D6"}},
        ],
    },
    {
        "slug": "zilveren-feest", "name": "Zilveren feest", "sort_order": 270,
        "tagline": "Ingetogen en chic, in zilvertinten",
        "description": "Een zilveren gordijn opent zich. Een kader met strakke lijnen, hoofdletters en de datum in cijfers.",
        "style_notes": "Zilver, kader, ingetogen chic",
        "occasions": ["jubileum", "bruiloft"],
        "atelier": {"opening": "gordijn", "hero": "kader", "sections": "lijnen", "heading": "kapitaal", "names": "kapitaal", "date": "cijfers", "photo": "rond", "texture": "linnen", "ornament": "geometrisch"},
        "effects": {"sfeer": "goudstof", "knal": "vonken", "viering": "vonken", "namen": "folie", "onthul": "zacht", "extra": ["stralen", "kantel"]},
        "fonts": {"display": "italiana", "body": "montserrat", "ui": "montserrat", "text": "instrument", "number": "instrument"},
        "preload": ["display", "body"],
        "tokens": {"--a-radius": "4px", "--a-names-spacing": ".16em"},
        "css": ".a-sec__body { font-size: 1rem; font-weight: 400; }\n.a-names { font-weight: 400; }",
        "palettes": [
            {"key": "zilver", "name": "Zilver", "colors": {"bg": "#F3F4F6", "surface": "#FFFFFF", "ink": "#22262B", "muted": "#58606A", "accent": "#56606C", "accent_ink": "#FFFFFF", "line": "#DDE0E4", "c2": "#D5DAE0", "c3": "#E9E4DC", "cover_bg": "#1F2329", "cover_ink": "#F3F4F6", "curtain": "#8A939E"}},
            {"key": "parel", "name": "Parel", "colors": {"bg": "#F7F5F2", "surface": "#FFFFFF", "ink": "#29251F", "muted": "#5F584F", "accent": "#665F55", "accent_ink": "#FFFFFF", "line": "#E4DFD8", "c2": "#E2DBD1", "c3": "#EEE8DF", "cover_bg": "#2B2722", "cover_ink": "#F7F5F2", "curtain": "#A59D92"}},
            {"key": "nacht", "name": "Nacht", "colors": {"bg": "#15181D", "surface": "#1D2128", "ink": "#EEF0F3", "muted": "#B8BEC7", "accent": "#C5CCD6", "accent_ink": "#15181D", "line": "#2E343E", "c2": "#C5CCD6", "c3": "#5B6472", "cover_bg": "#0F1115", "cover_ink": "#EEF0F3", "curtain": "#4A525E", "scheme": "dark"}},
        ],
    },
    {
        "slug": "gouden-jaren", "name": "Gouden jaren", "sort_order": 280,
        "tagline": "Groots, met een gouden getal",
        "description": "Een vouwkaart opent zich. Het aantal jaren in grote, sierlijke cijfers, fonkeling en onderdelen in twee kolommen.",
        "style_notes": "Ivoor en goud, groot getal, sierlijk",
        "occasions": ["jubileum", "verjaardag"],
        "atelier": {"opening": "vouwkaart", "hero": "getal", "sections": "tweekolom", "heading": "groot", "names": "cursief", "date": "kalender", "photo": "rond", "texture": "geen", "ornament": "fonkel"},
        "effects": {"sfeer": "goudstof", "knal": "vonken", "viering": "vonken", "namen": "folie", "onthul": "omhoog", "extra": ["stralen", "kantel"]},
        "fonts": {"display": "bodoni", "body": "lora", "ui": "tenor"},
        "preload": ["display", "body"],
        "tokens": {"--a-radius": "6px"},
        "css": ".a-number { font-style: italic; font-weight: 500; }\n.a-h2 { font-style: italic; }",
        "palettes": [
            {"key": "ivoor-goud", "name": "Ivoor & goud", "colors": {"bg": "#FBF7EE", "surface": "#FFFFFF", "ink": "#231D14", "muted": "#5A5043", "accent": "#7F5A1C", "accent_ink": "#FFFFFF", "line": "#EDE2CC", "c2": "#E2C27E", "c3": "#F3E6CF", "cover_bg": "#EFE3C8", "cover_ink": "#231D14"}},
            {"key": "bordeaux-goud", "name": "Bordeaux & goud", "colors": {"bg": "#2A0E14", "surface": "#36141C", "ink": "#F6EADB", "muted": "#D6C1B0", "accent": "#D9B46A", "accent_ink": "#2A0E14", "line": "#4A2029", "c2": "#D9B46A", "c3": "#8E5B4B", "cover_bg": "#1F0A0F", "cover_ink": "#F6EADB", "scheme": "dark"}},
            {"key": "groen-goud", "name": "Groen & goud", "colors": {"bg": "#0F2A22", "surface": "#15362C", "ink": "#F1ECDD", "muted": "#C9C6B4", "accent": "#D6B874", "accent_ink": "#0F2A22", "line": "#244A3E", "c2": "#D6B874", "c3": "#5F8A74", "cover_bg": "#0A1F19", "cover_ink": "#F1ECDD", "scheme": "dark"}},
        ],
    },
    {
        "slug": "door-de-jaren", "name": "Door de jaren", "sort_order": 290,
        "tagline": "Nostalgisch, met een tijdlijn",
        "description": "Een oude foto ontwikkelt zich na een tik. Typemachineletters, een tijdlijn voor het programma en foto's in sepia.",
        "style_notes": "Sepia, typemachine, tijdlijn",
        "occasions": ["jubileum", "verjaardag", "zakelijk"],
        "atelier": {"opening": "polaroid", "hero": "polaroid", "sections": "tijdlijn", "heading": "kapitaal", "names": "display", "date": "lijn", "photo": "polaroid", "texture": "papier", "ornament": "lijnen"},
        "effects": {"sfeer": "film", "knal": "flits", "viering": "confetti", "namen": "zacht", "onthul": "kanteling", "extra": ["kenburns"]},
        "fonts": {"display": "lora", "body": "lora", "script": "courier", "ui": "courier"},
        "preload": ["display", "ui"],
        "tokens": {"--a-radius": "2px"},
        "css": "body[data-palette=\"sepia\"] .ph__img { filter: sepia(.35) saturate(.85); }\nbody[data-palette=\"zwart-wit\"] .ph__img { filter: grayscale(1) contrast(1.05); }\n.a-photo__caption, .a-snap__caption { font-size: 1.1rem; }\n.a-tagline { font-family: var(--a-ui); font-style: normal; font-size: 1rem; }",
        "palettes": [
            {"key": "sepia", "name": "Sepia", "colors": {"bg": "#F3EBDD", "surface": "#FBF6EC", "ink": "#2B2118", "muted": "#5B4F41", "accent": "#734829", "accent_ink": "#FFFFFF", "line": "#DECFB6", "c2": "#D9C3A0", "c3": "#C9B79C", "cover_bg": "#E8DCC6", "cover_ink": "#2B2118"}},
            {"key": "zwart-wit", "name": "Zwart-wit", "colors": {"bg": "#F4F4F2", "surface": "#FFFFFF", "ink": "#1D1D1D", "muted": "#555555", "accent": "#2B2B2B", "accent_ink": "#FFFFFF", "line": "#DCDCD8", "c2": "#D9D9D5", "c3": "#EBEBE7", "cover_bg": "#E8E8E4", "cover_ink": "#1D1D1D"}},
            {"key": "blauw", "name": "Blauw", "colors": {"bg": "#EEF1F4", "surface": "#FFFFFF", "ink": "#1C2733", "muted": "#505C69", "accent": "#2E4A66", "accent_ink": "#FFFFFF", "line": "#D6DDE4", "c2": "#C7D3DF", "c3": "#E6E1D6", "cover_bg": "#E1E7ED", "cover_ink": "#1C2733"}},
        ],
    },
    {
        "slug": "robijn", "name": "Robijn", "sort_order": 300,
        "tagline": "Warm en romantisch, in robijnrood",
        "description": "Een cadeaulint wordt losgetrokken. Sierlijke cursieve namen, twee ringen, een ronde foto en kaartjes voor elk onderdeel.",
        "style_notes": "Robijnrood, ringen, cursief",
        "occasions": ["jubileum", "bruiloft", "verjaardag"],
        "atelier": {"opening": "lint", "hero": "klassiek", "sections": "kaarten", "heading": "lijn", "names": "cursief", "date": "blok", "photo": "cirkel", "texture": "geen", "ornament": "ringen"},
        "effects": {"sfeer": "blaadjes", "knal": "harten", "viering": "harten", "namen": "folie", "onthul": "zacht", "extra": ["kantel", "tik"]},
        "fonts": {"display": "playfair", "body": "figtree", "ui": "figtree"},
        "preload": ["display", "body"],
        "tokens": {"--a-radius": "12px"},
        "css": ".a-names { color: var(--a-text); }\n.a-lead { font-style: italic; }",
        "palettes": [
            {"key": "robijn", "name": "Robijn", "colors": {"bg": "#FBF3F3", "surface": "#FFFFFF", "ink": "#2D1B1F", "muted": "#665156", "accent": "#931A2E", "accent_ink": "#FFFFFF", "line": "#F0DADC", "c2": "#E8B9C0", "c3": "#F1DCC7", "cover_bg": "#F3E1E1", "cover_ink": "#2D1B1F", "ribbon": "#931A2E"}},
            {"key": "wijn", "name": "Wijn", "colors": {"bg": "#1E0A10", "surface": "#2A1018", "ink": "#F6E9E6", "muted": "#D2BBB7", "accent": "#E3B7A0", "accent_ink": "#1E0A10", "line": "#431A25", "c2": "#E3B7A0", "c3": "#8E3A4C", "cover_bg": "#16070C", "cover_ink": "#F6E9E6", "ribbon": "#B8324C", "scheme": "dark"}},
            {"key": "roze", "name": "Roze", "colors": {"bg": "#FDF1F3", "surface": "#FFFFFF", "ink": "#33202A", "muted": "#67535D", "accent": "#A0304F", "accent_ink": "#FFFFFF", "line": "#F4DAE0", "c2": "#F4C1CD", "c3": "#EFDCC8", "cover_bg": "#F8E1E6", "cover_ink": "#33202A", "ribbon": "#D9899C"}},
        ],
    },
    # ---------------------------------------------------------------- Babyshower
    {
        "slug": "wolkje", "name": "Wolkje", "sort_order": 310,
        "tagline": "Zacht en rond, met wolkjes",
        "description": "Laat de ballonnen los om te openen. Wolkjes, zachte kleuren, ronde kaartjes en de datum in een cirkel.",
        "style_notes": "Zachtblauw, wolkjes, rond",
        "occasions": ["babyshower", "verjaardag"],
        "atelier": {"opening": "ballonnen", "hero": "klassiek", "sections": "kaarten", "heading": "groot", "names": "display", "date": "cirkel", "photo": "cirkel", "texture": "geen", "ornament": "wolken"},
        "effects": {"sfeer": "wolkjes", "knal": "bellen", "viering": "bellen", "namen": "pop", "onthul": "zoom", "extra": ["tik"]},
        "fonts": {"display": "quicksand", "body": "nunito", "ui": "nunito"},
        "preload": ["display", "body"],
        "tokens": {"--a-radius": "24px", "--a-names-weight": "600", "--a-h2-weight": "600"},
        "css": ".a-tagline { font-family: var(--a-body); font-style: normal; }\n.a-lead { font-family: var(--a-body); }\n.a-sec-kaarten .a-sec { box-shadow: 0 14px 30px -24px color-mix(in srgb, var(--a-accent) 70%, transparent); }",
        "palettes": [
            {"key": "lichtblauw", "name": "Lichtblauw", "colors": {"bg": "#F2F7FC", "surface": "#FFFFFF", "ink": "#24303D", "muted": "#53606D", "accent": "#2C6599", "accent_ink": "#FFFFFF", "line": "#DCE8F4", "c2": "#CFE3F5", "c3": "#F6E3C8", "cover_bg": "#E4EFF9", "cover_ink": "#24303D"}},
            {"key": "roze", "name": "Roze", "colors": {"bg": "#FDF3F6", "surface": "#FFFFFF", "ink": "#35262D", "muted": "#66555D", "accent": "#A63A63", "accent_ink": "#FFFFFF", "line": "#F5DDE5", "c2": "#F7D3E0", "c3": "#D9EAF5", "cover_bg": "#FBE6EE", "cover_ink": "#35262D"}},
            {"key": "mint", "name": "Mint", "colors": {"bg": "#F1FAF6", "surface": "#FFFFFF", "ink": "#1F2E28", "muted": "#4F5F58", "accent": "#1C7053", "accent_ink": "#FFFFFF", "line": "#D6EDE3", "c2": "#CDEEDF", "c3": "#FCE7C8", "cover_bg": "#E1F4EB", "cover_ink": "#1F2E28"}},
        ],
    },
    {
        "slug": "maanlicht", "name": "Maanlicht", "sort_order": 320,
        "tagline": "Dromerig, met de maan en sterren",
        "description": "Een sterrenhemel schuift weg. Een maansikkel met sterren, sierlijke cursieve namen en zachte kleuren.",
        "style_notes": "Nachtblauw of lavendel, maan, sterren",
        "occasions": ["babyshower", "verloving"],
        "atelier": {"opening": "sterren", "hero": "klassiek", "sections": "midden", "heading": "ornament", "names": "cursief", "date": "blok", "photo": "cirkel", "texture": "sterren", "ornament": "sterren"},
        "effects": {"sfeer": "sterren", "knal": "sterren", "viering": "sterren", "namen": "zacht", "onthul": "zacht", "extra": ["tik"]},
        "fonts": {"display": "cormorant", "body": "quicksand", "ui": "quicksand"},
        "preload": ["display", "body"],
        "tokens": {"--a-names-weight": "500"},
        "css": ".a-sec__body { font-weight: 500; font-size: 1rem; }\n.a-names { color: var(--a-text); }",
        "palettes": [
            {"key": "nacht", "name": "Nacht", "colors": {"bg": "#1D2440", "surface": "#252D4D", "ink": "#F6F1E6", "muted": "#C9C7D2", "accent": "#F3D9A4", "accent_ink": "#1D2440", "line": "#343D63", "c2": "#F3D9A4", "c3": "#A9B8E0", "cover_bg": "#151B33", "cover_ink": "#F6F1E6", "scheme": "dark"}},
            {"key": "lavendel", "name": "Lavendel", "colors": {"bg": "#F5F2FA", "surface": "#FFFFFF", "ink": "#2B2640", "muted": "#5C5670", "accent": "#5C4B88", "accent_ink": "#FFFFFF", "line": "#E4DEF0", "c2": "#E7C98F", "c3": "#C9C1E3", "cover_bg": "#2B2640", "cover_ink": "#F5F2FA", "cover_btn": "#E7C98F", "cover_btn_ink": "#2B2640"}},
            {"key": "zachtblauw", "name": "Zachtblauw", "colors": {"bg": "#F0F4FA", "surface": "#FFFFFF", "ink": "#1F2B3D", "muted": "#505D6E", "accent": "#34578A", "accent_ink": "#FFFFFF", "line": "#DAE3EF", "c2": "#E7C98F", "c3": "#BFD0E8", "cover_bg": "#1E2E4A", "cover_ink": "#F0F4FA", "cover_btn": "#E7C98F", "cover_btn_ink": "#1E2E4A"}},
        ],
    },
    {
        "slug": "regenboog", "name": "Regenboog", "sort_order": 330,
        "tagline": "Vrolijk en naturel, met een regenboog",
        "description": "Een cadeau om uit te pakken: de strik gaat los, plof, en er springen cadeautjes uit. Een regenboog in aardetinten of pastel, een foto in boogvorm en rustige lijnen.",
        "style_notes": "Aardetinten, regenboog, zacht",
        "occasions": ["babyshower", "verjaardag"],
        "atelier": {"opening": "cadeau", "hero": "klassiek", "sections": "lijnen", "heading": "lijn", "names": "display", "date": "lijn", "photo": "boog", "texture": "geen", "ornament": "regenboog"},
        "effects": {"sfeer": "bellen", "knal": "cadeautjes", "viering": "cadeautjes", "namen": "zacht", "onthul": "zoom", "extra": ["aura", "tik"]},
        "fonts": {"display": "fraunces", "body": "quicksand", "ui": "quicksand"},
        "preload": ["display", "body"],
        "tokens": {"--a-radius": "14px", "--a-names-weight": "500"},
        "css": ".a-orn--top { width: min(12rem, 52vw); }\n.a-sec__body { font-weight: 500; }\n.a-tagline { font-family: var(--a-body); font-style: normal; font-weight: 500; }",
        "palettes": [
            {"key": "aarde", "name": "Aarde", "colors": {"bg": "#FBF6F0", "surface": "#FFFFFF", "ink": "#3A2B22", "muted": "#67564A", "accent": "#9C4E2C", "accent_ink": "#FFFFFF", "line": "#EFE2D4", "c2": "#E0A96D", "c3": "#9CAF88", "cover_bg": "#F3E6D8", "cover_ink": "#3A2B22"}},
            {"key": "pastel", "name": "Pastel", "colors": {"bg": "#FBF8F3", "surface": "#FFFFFF", "ink": "#2F2A33", "muted": "#615B66", "accent": "#7A4F8E", "accent_ink": "#FFFFFF", "line": "#EDE6EF", "c2": "#F5B8B8", "c3": "#A9D3E8", "cover_bg": "#F3EDF4", "cover_ink": "#2F2A33"}},
            {"key": "zee", "name": "Zee", "colors": {"bg": "#F2F6F8", "surface": "#FFFFFF", "ink": "#1D2B33", "muted": "#4F5E66", "accent": "#28607A", "accent_ink": "#FFFFFF", "line": "#DCE6EB", "c2": "#9CC5D6", "c3": "#E3C9A3", "cover_bg": "#E2ECF1", "cover_ink": "#1D2B33"}},
        ],
    },
    {
        "slug": "lentebloesem", "name": "Lentebloesem", "sort_order": 340,
        "tagline": "Lieflijk, met bloesem in een kader",
        "description": "Een envelop met zegel opent zich. Een kader met bloemen, sierlijk handschrift en elk onderdeel op een kaartje.",
        "style_notes": "Bloesem, kader, handschrift",
        "occasions": ["babyshower", "bruiloft", "verloving"],
        "atelier": {"opening": "envelop", "hero": "kader", "sections": "kaarten", "heading": "script", "names": "script", "date": "blok", "photo": "boog", "texture": "papier", "ornament": "bloemen"},
        "effects": {"sfeer": "bloesem", "knal": "bloesem", "viering": "bloesem", "namen": "schrijf", "onthul": "zacht", "extra": ["kenburns", "kantel", "tik"]},
        "fonts": {"display": "lora", "body": "lora", "script": "parisienne", "ui": "nunito"},
        "preload": ["script", "display"],
        "tokens": {"--a-names-font": "var(--a-script)", "--a-radius": "10px"},
        "css": ".a-names { color: var(--a-text); }\n.a-frame { border-radius: 4px; }\n.a-sec-kaarten .a-sec { box-shadow: none; border: 1px solid var(--a-line); }",
        "palettes": [
            {"key": "bloesem", "name": "Bloesem", "colors": {"bg": "#FDF6F4", "surface": "#FFFFFF", "ink": "#3A2A2C", "muted": "#695659", "accent": "#983E57", "accent_ink": "#FFFFFF", "line": "#F2DEDF", "c2": "#F4C9D2", "c3": "#D7E3CF", "cover_bg": "#F7E7E6", "cover_ink": "#3A2A2C", "env": "#F5DADE"}},
            {"key": "salie", "name": "Salie", "colors": {"bg": "#F4F6F1", "surface": "#FFFFFF", "ink": "#263024", "muted": "#555F52", "accent": "#4A6242", "accent_ink": "#FFFFFF", "line": "#DEE5D9", "c2": "#F1D3D9", "c3": "#CBD9C3", "cover_bg": "#E6ECE2", "cover_ink": "#263024", "env": "#DCE5D5"}},
            {"key": "boter", "name": "Boter", "colors": {"bg": "#FDF9EE", "surface": "#FFFFFF", "ink": "#2E2717", "muted": "#615846", "accent": "#7D5A12", "accent_ink": "#FFFFFF", "line": "#F0E7CF", "c2": "#F5D98F", "c3": "#D8E3CC", "cover_bg": "#F6EED8", "cover_ink": "#2E2717", "env": "#F2E6C3"}},
        ],
    },
    {
        "slug": "stipjes", "name": "Stipjes", "sort_order": 350,
        "tagline": "Speels, met stippen en een kleurband",
        "description": "Een cadeau met stippen om uit te pakken: plof, en de cadeautjes vliegen eruit. Een gekleurde band met stippen, ronde kaartjes en een kalenderblaadje voor de datum.",
        "style_notes": "Stippen, kleurband, speels",
        "occasions": ["babyshower", "verjaardag"],
        "atelier": {"opening": "cadeau", "hero": "band", "sections": "kaarten", "heading": "groot", "names": "display", "date": "kalender", "photo": "cirkel", "texture": "stippen", "ornament": "stippen"},
        "effects": {"sfeer": "cadeautjes", "knal": "cadeautjes", "viering": "cadeautjes", "namen": "pop", "onthul": "zoom", "extra": ["tik"]},
        "fonts": {"display": "fredoka", "body": "nunito", "ui": "nunito"},
        "preload": ["display", "body"],
        "tokens": {"--a-radius": "20px", "--a-names-weight": "600", "--a-h2-weight": "600"},
        "css": ".a-band { background-image: radial-gradient(color-mix(in srgb, var(--a-accent-ink) 22%, transparent) 3px, transparent 3.6px); background-size: 26px 26px; }\n.a-tagline { font-family: var(--a-body); font-style: normal; }\n.a-lead { font-family: var(--a-body); }",
        "palettes": [
            {"key": "roze", "name": "Roze", "colors": {"bg": "#FFF5F7", "surface": "#FFFFFF", "ink": "#33262B", "muted": "#66555C", "accent": "#B73A67", "accent_ink": "#FFFFFF", "line": "#F7DEE5", "c2": "#F9C6D4", "c3": "#FFE2A8", "cover_bg": "#FFE9EF", "cover_ink": "#33262B"}},
            {"key": "blauw", "name": "Blauw", "colors": {"bg": "#F3F8FF", "surface": "#FFFFFF", "ink": "#1F2A3D", "muted": "#505C70", "accent": "#2B58B8", "accent_ink": "#FFFFFF", "line": "#DCE7F7", "c2": "#C8DAFF", "c3": "#FFE2A8", "cover_bg": "#E5EEFD", "cover_ink": "#1F2A3D"}},
            {"key": "geel", "name": "Geel", "colors": {"bg": "#FFFBEF", "surface": "#FFFFFF", "ink": "#2E2715", "muted": "#615843", "accent": "#7F5C00", "accent_ink": "#FFFFFF", "line": "#F3EACB", "c2": "#FFE08A", "c3": "#BDE3F0", "cover_bg": "#FFF3CF", "cover_ink": "#2E2715"}},
        ],
    },
    # ---------------------------------------------------------------- Zakelijk
    {
        "slug": "strak", "name": "Strak zakelijk", "sort_order": 360,
        "tagline": "Helder en professioneel",
        "description": "Een paneel schuift opzij. Grote, strakke letters, de feiten in kolommen, genummerde onderdelen en een kalenderblaadje.",
        "style_notes": "Marine, strak, professioneel",
        "occasions": ["zakelijk", "jubileum"],
        "atelier": {"opening": "schuif", "hero": "redactioneel", "sections": "genummerd", "heading": "kapitaal", "names": "display", "date": "kalender", "photo": "recht", "texture": "geen", "ornament": "geen"},
        "effects": {"sfeer": "raster", "knal": "lijnen", "viering": "lijnen", "namen": "zacht", "onthul": "wissel", "extra": []},
        "fonts": {"display": "manrope", "body": "manrope", "ui": "manrope"},
        "preload": ["display"],
        "tokens": {"--a-radius": "6px", "--a-names-weight": "700", "--a-names-spacing": "-.035em", "--a-h2-weight": "700"},
        "css": ".a-tagline { font-family: var(--a-body); font-style: normal; }\n.a-lead { font-family: var(--a-body); font-size: 1.2rem; }\n.a-program__what h3, .a-location__venue, .a-contact__name, .cd__num { font-weight: 700; }",
        "palettes": [
            {"key": "marine", "name": "Marine", "colors": {"bg": "#F6F7F9", "surface": "#FFFFFF", "ink": "#111A2B", "muted": "#4E5869", "accent": "#1F3A68", "accent_ink": "#FFFFFF", "line": "#D9DEE6", "c2": "#C9D5EA", "c3": "#E8EDF5", "cover_bg": "#1F3A68", "cover_ink": "#FFFFFF"}},
            {"key": "antraciet", "name": "Antraciet", "colors": {"bg": "#F5F5F4", "surface": "#FFFFFF", "ink": "#1A1A1A", "muted": "#555553", "accent": "#2E2E2E", "accent_ink": "#FFFFFF", "line": "#DEDEDC", "c2": "#D6D6D3", "c3": "#EBEBE9", "cover_bg": "#2E2E2E", "cover_ink": "#FFFFFF"}},
            {"key": "bosgroen", "name": "Bosgroen", "colors": {"bg": "#F3F6F4", "surface": "#FFFFFF", "ink": "#12211B", "muted": "#4D5B55", "accent": "#1F5140", "accent_ink": "#FFFFFF", "line": "#D8E1DC", "c2": "#C6D8CF", "c3": "#E7EDE9", "cover_bg": "#1F5140", "cover_ink": "#FFFFFF"}},
        ],
    },
    {
        "slug": "gala", "name": "Gala", "sort_order": 370,
        "tagline": "Stijlvol en avondlijk, met een groot doek",
        "description": "Een fluwelen gordijn opent zich. Een grote foto met de titel erop, hoofdletters, fonkeling en een donkere achtergrond.",
        "style_notes": "Zwart en champagne, fluweel, avond",
        "occasions": ["zakelijk", "bruiloft", "jubileum"],
        "atelier": {"opening": "gordijn", "hero": "volbeeld", "sections": "midden", "heading": "kapitaal", "names": "kapitaal", "date": "cijfers", "photo": "rond", "texture": "geen", "ornament": "fonkel"},
        "effects": {"sfeer": "goudstof", "knal": "vonken", "viering": "vonken", "namen": "folie", "onthul": "zoom", "extra": ["stralen", "kenburns", "kantel"]},
        "fonts": {"display": "bodoni", "body": "tenor", "ui": "tenor"},
        "preload": ["display", "body"],
        "tokens": {"--a-radius": "4px", "--a-names-spacing": ".16em"},
        "css": ".a-hero__bg::after { background: linear-gradient(180deg, color-mix(in srgb, var(--a-cover-bg) 74%, transparent), color-mix(in srgb, var(--a-cover-bg) 90%, transparent)); }\n.a-names { font-weight: 500; }",
        "palettes": [
            {"key": "zwart-champagne", "name": "Zwart & champagne", "colors": {"bg": "#0D0D0D", "surface": "#171717", "ink": "#F4EEE4", "muted": "#CCC3B6", "accent": "#D8C3A0", "accent_ink": "#0D0D0D", "line": "#33302B", "c2": "#D8C3A0", "c3": "#6D6250", "cover_bg": "#080808", "cover_ink": "#F4EEE4", "curtain": "#4A0F1C", "scheme": "dark"}},
            {"key": "nachtblauw", "name": "Nachtblauw", "colors": {"bg": "#0B1224", "surface": "#131C33", "ink": "#F1ECE1", "muted": "#C3C0B8", "accent": "#CDB67E", "accent_ink": "#0B1224", "line": "#27304A", "c2": "#CDB67E", "c3": "#4E5B7C", "cover_bg": "#070C18", "cover_ink": "#F1ECE1", "curtain": "#1B2A55", "scheme": "dark"}},
            {"key": "bordeaux", "name": "Bordeaux", "colors": {"bg": "#1F0A0F", "surface": "#2A1016", "ink": "#F5EAE2", "muted": "#D0BDB4", "accent": "#D6B07A", "accent_ink": "#1F0A0F", "line": "#43202A", "c2": "#D6B07A", "c3": "#7E3A48", "cover_bg": "#16070B", "cover_ink": "#F5EAE2", "curtain": "#5A1422", "scheme": "dark"}},
        ],
    },
    {
        "slug": "congres", "name": "Congres", "sort_order": 380,
        "tagline": "Overzichtelijk, met het programma centraal",
        "description": "Een paneel schuift opzij. Een gekleurde band met de titel, een tijdlijn voor het programma en een lichte ruitstructuur.",
        "style_notes": "Blauw, tijdlijn, overzichtelijk",
        "occasions": ["zakelijk", "jubileum"],
        "atelier": {"opening": "schuif", "hero": "band", "sections": "tijdlijn", "heading": "groot", "names": "display", "date": "kalender", "photo": "rond", "texture": "ruit", "ornament": "geometrisch"},
        "effects": {"sfeer": "netwerk", "knal": "netwerk", "viering": "lijnen", "namen": "zacht", "onthul": "omhoog", "extra": []},
        "fonts": {"display": "syne", "body": "manrope", "ui": "manrope"},
        "preload": ["display", "body"],
        "tokens": {"--a-radius": "10px", "--a-names-weight": "700", "--a-h2-weight": "700", "--a-names-spacing": "-.02em"},
        "css": ".a-tagline { font-family: var(--a-body); font-style: normal; }\n.a-lead { font-family: var(--a-body); }\n.a-program__what h3 { font-family: var(--a-body); font-weight: 700; font-size: 1.1rem; }",
        "palettes": [
            {"key": "blauw", "name": "Blauw", "colors": {"bg": "#F4F6FB", "surface": "#FFFFFF", "ink": "#10182E", "muted": "#4D5670", "accent": "#243B8F", "accent_ink": "#FFFFFF", "line": "#DADFF0", "c2": "#C7D1F2", "c3": "#E6EAF7", "cover_bg": "#243B8F", "cover_ink": "#FFFFFF"}},
            {"key": "groen", "name": "Groen", "colors": {"bg": "#F2F6F3", "surface": "#FFFFFF", "ink": "#11231B", "muted": "#4B5B53", "accent": "#1E5B45", "accent_ink": "#FFFFFF", "line": "#D7E2DB", "c2": "#C2DACE", "c3": "#E5EEE8", "cover_bg": "#1E5B45", "cover_ink": "#FFFFFF"}},
            {"key": "oranje", "name": "Oranje", "colors": {"bg": "#FBF5F0", "surface": "#FFFFFF", "ink": "#2A1A10", "muted": "#64544A", "accent": "#A13F17", "accent_ink": "#FFFFFF", "line": "#F0E1D5", "c2": "#F2C4A8", "c3": "#F6E9DE", "cover_bg": "#A13F17", "cover_ink": "#FFFFFF"}},
        ],
    },
    {
        "slug": "borrel", "name": "Borrel", "sort_order": 390,
        "tagline": "Ontspannen en modern, met golven",
        "description": "Een vouwkaart opent zich. Stevige letters, golvende lijnen, een ronde foto naast de tekst en de datum in een cirkel.",
        "style_notes": "Koraal, golven, ontspannen",
        "occasions": ["zakelijk", "verjaardag"],
        "atelier": {"opening": "vouwkaart", "hero": "gesplitst", "sections": "kaarten", "heading": "groot", "names": "display", "date": "cirkel", "photo": "rond", "texture": "geen", "ornament": "golven"},
        "effects": {"sfeer": "champagne", "knal": "champagne", "viering": "champagne", "namen": "pop", "onthul": "wissel", "extra": ["kantel", "tik"]},
        "fonts": {"display": "fraunces", "body": "jost", "ui": "jost"},
        "preload": ["display", "body"],
        "tokens": {"--a-radius": "16px", "--a-names-weight": "650", "--a-h2-weight": "600"},
        "css": ".a-tagline { font-family: var(--a-body); font-style: normal; }\n.a-names { letter-spacing: -.025em; }",
        "palettes": [
            {"key": "koraal", "name": "Koraal", "colors": {"bg": "#FFF5F1", "surface": "#FFFFFF", "ink": "#2B1D18", "muted": "#66524A", "accent": "#A83E24", "accent_ink": "#FFFFFF", "line": "#F4E0D8", "c2": "#F7C1AF", "c3": "#A7D3CF", "cover_bg": "#FBE3DA", "cover_ink": "#2B1D18"}},
            {"key": "petrol", "name": "Petrol", "colors": {"bg": "#F0F6F6", "surface": "#FFFFFF", "ink": "#132628", "muted": "#4A5C5E", "accent": "#1B6168", "accent_ink": "#FFFFFF", "line": "#D6E6E6", "c2": "#A7D3CF", "c3": "#F7C1AF", "cover_bg": "#DCEDED", "cover_ink": "#132628"}},
            {"key": "mosterd", "name": "Mosterd", "colors": {"bg": "#FBF7EC", "surface": "#FFFFFF", "ink": "#2A2414", "muted": "#5F5744", "accent": "#7C5807", "accent_ink": "#FFFFFF", "line": "#EFE6CC", "c2": "#F2D27A", "c3": "#B9D3C6", "cover_bg": "#F4EACB", "cover_ink": "#2A2414"}},
        ],
    },
    {
        "slug": "mijlpaal", "name": "Mijlpaal", "sort_order": 400,
        "tagline": "Trots en krachtig, met een groot getal",
        "description": "Een cadeaulint wordt losgetrokken. Een groot getal of monogram, strakke hoofdletters en onderdelen in twee kolommen.",
        "style_notes": "Grafiet en goud, groot getal, krachtig",
        "occasions": ["zakelijk", "jubileum"],
        "atelier": {"opening": "lint", "hero": "getal", "sections": "tweekolom", "heading": "kapitaal", "names": "display", "date": "cijfers", "photo": "recht", "texture": "geen", "ornament": "geometrisch"},
        "effects": {"sfeer": "goudstof", "knal": "kanon", "viering": "vonken", "namen": "folie", "onthul": "omhoog", "extra": ["stralen"]},
        "fonts": {"display": "montserrat", "body": "lora", "ui": "montserrat"},
        "preload": ["display", "body"],
        "tokens": {"--a-radius": "4px", "--a-names-weight": "700", "--a-names-spacing": "-.02em"},
        "css": ".a-number { font-weight: 800; letter-spacing: -.05em; }\n.a-tagline { font-style: italic; font-family: var(--a-body); }",
        "palettes": [
            {"key": "grafiet-goud", "name": "Grafiet & goud", "colors": {"bg": "#F5F4F1", "surface": "#FFFFFF", "ink": "#1E1E1C", "muted": "#575651", "accent": "#735B2E", "accent_ink": "#FFFFFF", "line": "#E1DED7", "c2": "#E3D6BB", "c3": "#EAE8E2", "cover_bg": "#EDEAE3", "cover_ink": "#1E1E1C", "ribbon": "#735B2E"}},
            {"key": "marine-goud", "name": "Marine & goud", "colors": {"bg": "#101B2E", "surface": "#172440", "ink": "#F2EEE6", "muted": "#C3C4C6", "accent": "#D1B375", "accent_ink": "#101B2E", "line": "#26365A", "c2": "#D1B375", "c3": "#3D5687", "cover_bg": "#0B1322", "cover_ink": "#F2EEE6", "ribbon": "#D1B375", "scheme": "dark"}},
            {"key": "wit-blauw", "name": "Wit & blauw", "colors": {"bg": "#FFFFFF", "surface": "#F4F7FC", "ink": "#0F1B33", "muted": "#4D5A70", "accent": "#2451A6", "accent_ink": "#FFFFFF", "line": "#DDE4F0", "c2": "#C9D8F2", "c3": "#EEF2F9", "cover_bg": "#EEF2F9", "cover_ink": "#0F1B33", "ribbon": "#2451A6"}},
        ],
    },
    # ---------------------------------------------------------------- Kerst
    {
        "slug": "kerstman", "name": "Ho ho ho", "sort_order": 45,
        "tagline": "Vrolijk, met de kerstman en een cadeau",
        "description": "Een kerstcadeau om uit te pakken: plof, en de cadeautjes vliegen eruit. De kerstman met hulst, sneeuw die zacht valt en een kalenderblaadje voor de datum.",
        "style_notes": "Kerstrood, kerstman, hulst, sneeuw",
        "occasions": ["kerst"],
        # c3 is het groen van de hulstblaadjes naast de kerstman.
        "atelier": {"opening": "cadeau", "hero": "klassiek", "sections": "kaarten", "heading": "script", "names": "script", "date": "kalender", "photo": "cirkel", "texture": "stippen", "ornament": "kerstman"},
        "effects": {"sfeer": "sneeuw", "knal": "cadeautjes", "viering": "sneeuw", "namen": "pop", "onthul": "zoom", "extra": ["tik"]},
        "fonts": {"display": "fredoka", "body": "nunito", "script": "caveat", "ui": "nunito", "text": "nunito"},
        "preload": ["display", "body", "script"],
        "tokens": {"--a-radius": "18px", "--a-names-weight": "600", "--a-h2-weight": "600"},
        # De kerstman staat bovenaan en onderaan de kaart; hij zwaait en wiegt (alleen met beweging aan).
        "css": ".a-orn--top { width: min(11rem, 48vw); margin-bottom: .6rem; }\n.a-orn--bottom { display: none; }\n.a-orn--closing { width: min(8rem, 36vw); }\n"
               ".ks-arm { transform-box: view-box; transform-origin: 66px 112px; }\n.ks-figuur, .ks-hoofd { transform-box: view-box; transform-origin: 100px 220px; }\n"
               ".fx-motion .ks-arm { animation: ks-zwaai 1.8s ease-in-out infinite; animation-play-state: var(--fx-play, running); }\n"
               ".fx-motion .ks-figuur, .fx-motion .ks-hoofd { animation: ks-wieg 3.6s ease-in-out infinite; animation-play-state: var(--fx-play, running); }\n"
               ".fx-motion .ks-hoofd { animation-name: ks-knik; }\n"
               "@keyframes ks-zwaai { 0%, 100% { transform: rotate(0deg); } 20% { transform: rotate(-16deg); } 40% { transform: rotate(4deg); } 60% { transform: rotate(-14deg); } 80% { transform: rotate(2deg); } }\n"
               "@keyframes ks-wieg { 0%, 100% { transform: rotate(0deg); } 50% { transform: rotate(1.5deg); } }\n"
               "@keyframes ks-knik { 0%, 100% { transform: rotate(0deg); } 50% { transform: rotate(3deg); } }\n.a-tagline { font-family: var(--a-body); font-style: normal; }\n.a-lead { font-family: var(--a-body); }",
        "palettes": [
            {"key": "kerstrood", "name": "Kerstrood", "colors": {"bg": "#FFF8F1", "surface": "#FFFFFF", "ink": "#2B1414", "muted": "#6A4E4A", "accent": "#A3122A", "accent_ink": "#FFFFFF", "line": "#F1DED4", "c2": "#F4C9C2", "c3": "#2E6B3F", "cover_bg": "#FBE9E1", "cover_ink": "#2B1414", "wrap": "#B3152F", "ribbon": "#E9C46A"}},
            {"key": "sneeuwwit", "name": "Sneeuwwit", "colors": {"bg": "#F6FAFD", "surface": "#FFFFFF", "ink": "#14233A", "muted": "#4F5D70", "accent": "#A3122A", "accent_ink": "#FFFFFF", "line": "#DDE7F0", "c2": "#CFE0EE", "c3": "#2E6B3F", "cover_bg": "#E8F1F8", "cover_ink": "#14233A", "wrap": "#FFFFFF", "ribbon": "#B3152F"}},
            {"key": "dennengroen", "name": "Dennengroen", "colors": {"bg": "#F2F6F1", "surface": "#FFFFFF", "ink": "#13261B", "muted": "#4B5C52", "accent": "#1F5B3A", "accent_ink": "#FFFFFF", "line": "#D7E3DA", "c2": "#CFE3D3", "c3": "#2E6B3F", "cover_bg": "#1F5B3A", "cover_ink": "#FFFFFF", "wrap": "#1F5B3A", "ribbon": "#C8102E"}},
            {"key": "nachtblauw", "name": "Nachtblauw", "colors": {"bg": "#0E1730", "surface": "#16213F", "ink": "#F4EFE6", "muted": "#C5C6CC", "accent": "#E7C36A", "accent_ink": "#0E1730", "line": "#26335A", "c2": "#E7C36A", "c3": "#5FA37A", "cover_bg": "#0A1126", "cover_ink": "#F4EFE6", "wrap": "#A3122A", "ribbon": "#E7C36A", "scheme": "dark"}},
        ],
    },
    {
        "slug": "sneeuwpop", "name": "Sneeuwpret", "sort_order": 46,
        "tagline": "Ijzig en vrolijk, met een zwaaiende sneeuwpop",
        "description": "Een vouwkaart opent zich in een sneeuwbui. Een warm aangeklede sneeuwpop met hoge hoed, rode sjaal en wanten zwaait je toe tussen verlichte kerstbomen, in een kader van ijs.",
        "style_notes": "IJsblauw, sneeuwpop, sterren, winters",
        "occasions": ["kerst"],
        # Warm aangekleed (rode sjaal en wanten), met aan weerszijden verlichte kerstbomen.
        "atelier": {"opening": "vouwkaart", "hero": "kader", "sections": "midden", "heading": "ornament", "names": "display", "date": "cirkel", "photo": "boog", "texture": "sterren", "ornament": "sneeuwpop"},
        "effects": {"sfeer": "sneeuw", "knal": "sneeuw", "viering": "sterren", "namen": "gloed", "onthul": "zacht", "extra": ["tik"]},
        "fonts": {"display": "fraunces", "body": "quicksand", "ui": "quicksand", "text": "quicksand"},
        "preload": ["display", "body"],
        "tokens": {"--a-radius": "22px", "--a-names-weight": "600", "--a-h2-weight": "600"},
        "css": ".a-orn--top { width: min(14rem, 62vw); margin-bottom: .6rem; }\n.a-orn--bottom { display: none; }\n.a-orn--closing { width: min(10rem, 46vw); }\n"
               ".fx-motion .sp-lamp { animation: sp-twinkel 1.6s ease-in-out infinite; animation-play-state: var(--fx-play, running); }\n"
               ".fx-motion .sp-lamp--1 { animation-delay: -.55s; }\n.fx-motion .sp-lamp--2 { animation-delay: -1.1s; }\n"
               "@keyframes sp-twinkel { 0%, 100% { opacity: 1; } 50% { opacity: .35; } }\n"
               ".sp-arm { transform-box: view-box; transform-origin: 70px 116px; }\n.sp-hoed { transform-box: view-box; transform-origin: 100px 46px; }\n"
               ".sp-sjaal { transform-box: view-box; transform-origin: 110px 96px; }\n.sp-figuur { transform-box: view-box; transform-origin: 100px 222px; }\n"
               ".fx-motion .sp-arm { animation: sp-zwaai 2s ease-in-out infinite; animation-play-state: var(--fx-play, running); }\n"
               ".fx-motion .sp-hoed { animation: sp-hoed 4s ease-in-out infinite; animation-play-state: var(--fx-play, running); }\n"
               ".fx-motion .sp-sjaal { animation: sp-sjaal 1.4s ease-in-out infinite; animation-play-state: var(--fx-play, running); }\n"
               ".fx-motion .sp-figuur { animation: sp-wieg 4s ease-in-out infinite; animation-play-state: var(--fx-play, running); }\n"
               "@keyframes sp-zwaai { 0%, 100% { transform: rotate(0deg); } 25% { transform: rotate(18deg); } 50% { transform: rotate(-4deg); } 75% { transform: rotate(16deg); } }\n"
               "@keyframes sp-hoed { 0%, 70%, 100% { transform: rotate(0deg); } 80% { transform: rotate(-9deg) translateY(-3px); } 90% { transform: rotate(4deg); } }\n"
               "@keyframes sp-sjaal { 0%, 100% { transform: rotate(0deg); } 50% { transform: rotate(-8deg); } }\n"
               "@keyframes sp-wieg { 0%, 100% { transform: rotate(-1deg); } 50% { transform: rotate(1deg); } }\n"
               ".a-tagline { font-family: var(--a-body); font-style: normal; }\n.a-lead { font-family: var(--a-body); }",
        "palettes": [
            {"key": "ijsblauw", "name": "IJsblauw", "colors": {"bg": "#F1F7FC", "surface": "#FFFFFF", "ink": "#12243A", "muted": "#4B5E74", "accent": "#1F5E99", "accent_ink": "#FFFFFF", "line": "#D6E5F2", "c2": "#BFD9EE", "c3": "#E3EFF8", "cover_bg": "#DCEBF7", "cover_ink": "#12243A"}},
            {"key": "zilverwit", "name": "Zilverwit", "colors": {"bg": "#F7F7F9", "surface": "#FFFFFF", "ink": "#1E2027", "muted": "#555866", "accent": "#8E1B2C", "accent_ink": "#FFFFFF", "line": "#E2E3E8", "c2": "#D5D8E0", "c3": "#EDEEF2", "cover_bg": "#E9EAEF", "cover_ink": "#1E2027"}},
            {"key": "mint", "name": "Mint", "colors": {"bg": "#F0F8F5", "surface": "#FFFFFF", "ink": "#11271F", "muted": "#48605A", "accent": "#1C6B55", "accent_ink": "#FFFFFF", "line": "#D3E8E0", "c2": "#BFE0D3", "c3": "#E2F2EC", "cover_bg": "#D8EEE6", "cover_ink": "#11271F"}},
            {"key": "poolnacht", "name": "Poolnacht", "colors": {"bg": "#141A36", "surface": "#1D2447", "ink": "#EEF2FA", "muted": "#C1C7D8", "accent": "#8FD3F0", "accent_ink": "#141A36", "line": "#2D3664", "c2": "#8FD3F0", "c3": "#3B4680", "cover_bg": "#0E1329", "cover_ink": "#EEF2FA", "scheme": "dark"}},
        ],
    },
]
