# Generated by Django 5.2.17 on 2026-09-29 11:26

from django.db import migrations, models


def balzaal_is_special(apps, schema_editor):
    # Balzaal (september 2026) is de eerste special; nieuwe ontwerpen krijgen het uit hun manifest.
    apps.get_model("catalog", "Template").objects.filter(slug="balzaal").update(special=True)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_persoonlijk_zegel'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='special',
            field=models.BooleanField(default=False, help_text="Bijzonder ontwerp: staat onder Specials, niet tussen de gewone kaarten, en heeft een eigen meerprijs (extra optie met functie 'special' en code special-<code>). Zonder die optie is het niet te bestellen.", verbose_name='special'),
        ),
        migrations.RunPython(balzaal_is_special, migrations.RunPython.noop),
    ]
