# Generated by Django 5.2.17 on 2026-09-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_gelegenheid_kerst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='kind',
            field=models.CharField(choices=[('photo', 'Foto'), ('audio', 'Muziek'), ('scene', 'Eigen bruidspaar')], max_length=10),
        ),
    ]
