# Generated by Django 5.2.17 on 2026-09-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_invitation_package_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='draft_updated_source',
            field=models.CharField(choices=[('customer', 'Klant'), ('admin', 'VAYLIDE-team'), ('system', 'Systeem'), ('restore', 'Hersteld')], default='customer', max_length=12),
        ),
        migrations.AlterField(
            model_name='invitationversion',
            name='source',
            field=models.CharField(choices=[('customer', 'Klant'), ('admin', 'VAYLIDE-team'), ('system', 'Systeem'), ('restore', 'Hersteld')], max_length=12),
        ),
    ]
