# Generated by Django 5.2.17 on 2026-09-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0007_merknaam_hoofdletters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='kind',
            field=models.CharField(choices=[('photo', 'Foto'), ('audio', 'Muziek'), ('scene', 'Eigen bruidspaar'), ('logo', 'Logo op het zegel')], max_length=10),
        ),
    ]
