# Generated by Django 5.2.17 on 2026-09-29 21:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='toestemming directe levering'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_consent_text',
            field=models.TextField(blank=True, verbose_name='tekst toestemming'),
        ),
        migrations.AddField(
            model_name='order',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='online tot en met'),
        ),
        migrations.AddField(
            model_name='order',
            name='terms_version',
            field=models.CharField(blank=True, max_length=20, verbose_name='versie voorwaarden'),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='naam')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mailadres')),
                ('order_number', models.CharField(blank=True, max_length=40, verbose_name='bestelnummer')),
                ('product', models.CharField(blank=True, max_length=200, verbose_name='product of dienst')),
                ('order_date', models.CharField(blank=True, max_length=40, verbose_name='besteldatum')),
                ('note', models.TextField(blank=True, verbose_name='toelichting')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ontvangen op')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='afgehandeld op')),
                ('handled_note', models.TextField(blank=True, verbose_name='notitie afhandeling')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='orders.order')),
            ],
            options={
                'verbose_name': 'herroeping',
                'verbose_name_plural': 'herroepingen',
                'ordering': ['-created_at'],
            },
        ),
    ]
