# Generated by Django 5.2.17 on 2026-10-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_voorwaarden_en_herroepen'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='verzoek start online dienst'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_consent_text',
            field=models.TextField(blank=True, verbose_name='tekst verzoek start online dienst'),
        ),
    ]
